# Generated by Django 5.2.4 on 2025-07-26 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=256)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('categoria', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegracaoSympla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('requisicao', models.JSONField()),
                ('status_code', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Integrações Sympla',
            },
        ),
        migrations.CreateModel(
            name='EventoSympla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id_sympla', models.CharField(max_length=7)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.evento')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.integracaosympla')),
            ],
            options={
                'verbose_name_plural': 'Eventos Sympla',
            },
        ),
    ]
