# Generated by Django 5.2.4 on 2025-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosympla',
            name='reference_id',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
